#!/bin/bash

interface=wlp0s20f3                             # nome da interface
ip=2804:1b3:a300:c94e:5f0c:b1b3:8a5e:3954       # endereco IPv6 completo

# remove ultimos dois caracteres
prefix=${ip%??}

for i in {0..9} a b c d e f; do
    for j in {0..9} a b c d e f; do
        # varia ultimos dois caracteres
        ip addr add noprefixroute $prefix$i$j/64 dev $interface
    done
done
