services:
  mongo:
    build:
      context: ./mongo
    restart: always
    ports:
      - "8090:27017"
    volumes:
      - db:/data/db
      - configdb:/data/configdb
      - ./dados:/dados

  redis:
    image: redis:latest
    restart: always
    ports:
      - "8091:6379"
    volumes:
      - redis:/data

  scraper:
    build:
      context: ./scraper
    depends_on:
      - mongo
      - redis
    environment:
      - MONGO_HOST=mongodb://mongo:27017/
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DADOS_DIR=/dados
    volumes:
      - ./scraper:/app
      - ./dados:/dados
    entrypoint: python main.py
    stdin_open: true
    tty: true

  mongosh:
    build:
      context: ./mongosh
    depends_on:
      - mongo
    stdin_open: true
    tty: true
    volumes:
      - db:/data/db
      - configdb:/data/configdb

volumes:
  db:
  configdb:
  redis: