services:
  db:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - db:/data/db

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

  shell:
    build: .
    network_mode: host
    depends_on:
      - db
    # environment:
    #   - MONGO_HOST=mongodb://db:27017
    volumes:
      - .:/app
    stdin_open: true
    tty: true

volumes:
  db:
  redis_data: