services:
  db:
    image: mongo
    restart: always
    ports:
      - "8090:27017"
    volumes:
      - db:/data/db

  redis:
    image: redis:latest
    ports:
      - "8091:6379"
    volumes:
      - redis_data:/data
    restart: always

  scraper:
    build:
      context: ./scraper
    network_mode: host
    depends_on:
      - db
      - redis
    environment:
      - MONGO_HOST=mongodb://localhost:8090
      - REDIS_HOST=localhost
      - REDIS_PORT=8091
      - DADOS_DIR=/dados
    volumes:
      - ./scraper:/app
      - ./dados:/dados
    entrypoint: python main.py

  mongosh:
    build:
      context: ./mongosh
    depends_on:
      - db
    stdin_open: true
    tty: true

volumes:
  db:
  redis_data: